### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sjkim0** [sjkim0/mmWave#2]
- [x] stm32firmware project init
- [x] HLK-LD2450 board tx rx test
- [ ] mmWave TEST
- [ ] window application for radar init
